export const defaultTheme = {
  fontColorBlack: "#333333",
  colorWhite: "#ffffff",
  colorRed: "#FF2400",
  bcgrCardColor: "#edd3ba",
  bcgrCardInfoColor: "#DEB887",
  btnTextColor: "#eeeeee",
  btnHoverTextColor: "#edd70c",
  widthPhotoHero: "270px",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  pageWidth: "1280px",
};
